import { DocumentData, ChatMessage } from '../types';
import { computeContractHealth } from '../components/ContractHealthGauge';

export function generateAuditReportMarkdown(doc: DocumentData, messages?: ChatMessage[]): string {
  const health = computeContractHealth(doc);
  const now = new Date().toLocaleString();

  let mathSection = '';
  if (doc.projections) {
    const p = doc.projections;
    const engine = p.engine || 'compound_penalty';

    if (engine === 'loan_emi_foreclosure') {
      mathSection = `### 4. Verified Deterministic Loan Amortization Schedule
- **Monthly EMI:** ₹${p.monthlyEmi?.toLocaleString()}
- **Loan Principal:** ₹${p.principal?.toLocaleString()} (@ ${p.annualInterestRatePercent}% p.a.)
- **Total Interest:** ₹${p.totalInterest?.toLocaleString()} (Total Payback: ₹${p.totalPayment?.toLocaleString()})
- **Lock-in Period:** ${p.lockInPeriodMonths} Months (Zero early prepayment permitted in Year 1)
- **Early Foreclosure Penalty:** ${p.foreclosureChargePercent}% + 18% GST

| Timeline | Remaining Principal | Early Exit Fee | Total to Close Loan |
| :--- | :--- | :--- | :--- |
${p.milestones?.map((m: any) => `| Month ${m.month} | ₹${m.remainingPrincipal?.toLocaleString()} | ${m.isLockInActive ? 'Locked (Disallowed)' : `₹${m.totalForeclosureCost?.toLocaleString()}`} | ₹${m.totalToCloseLoan?.toLocaleString()} |`).join('\n') || ''}

*Calculation Narrative:* ${p.narrative}
`;
    } else if (engine === 'tiered_power_tariff') {
      mathSection = `### 4. Verified Telescopic Utility Tariff Breakdown
- **Total Net Bill:** ₹${p.totalNetBill?.toLocaleString()}
- **Units Consumed:** ${p.unitsKwh?.toLocaleString()} kWh
- **Sanctioned Load:** ${p.sanctionedLoadKw} kW
- **Energy Charges:** ₹${p.energyCharge?.toLocaleString()}
- **Fixed Demand Charge:** ₹${p.fixedCharge?.toLocaleString()}
- **Fuel Adjustment (FAC):** ₹${p.fuelAdjustmentCharge?.toLocaleString()}
- **State Duty (${p.dutyPercent}%):** ₹${p.electricityDuty?.toLocaleString()}

| Slab Tier | Billed Units | Rate per Unit | Slab Charge |
| :--- | :--- | :--- | :--- |
${p.slabBreakdown?.map((s: any) => `| ${s.label} | ${s.units} kWh | ₹${s.ratePerUnit?.toFixed(2)} | ₹${s.charge?.toLocaleString()} |`).join('\n') || ''}

*Calculation Narrative:* ${p.narrative}
`;
    } else {
      mathSection = `### 4. Verified Compounding Overdue Penalty Schedule
- **Base Principal:** ₹${p.principal?.toLocaleString()}
- **Annual Rate:** ${p.annualRatePercent}% p.a.
- **Flat Monthly Late Fee:** ₹${p.flatPenaltyPerMonth || 0}/mo
- **Formula:** A = P(1 + r/n)^(nt) + (flatFees * t)

| Duration | Interest Accrued | Flat Late Fees | Total Penalty | Total Liability | Increase |
| :--- | :--- | :--- | :--- | :--- | :--- |
${p.projections?.map((item: any) => `| ${item.months} Month${item.months > 1 ? 's' : ''} | ₹${item.interestAccrued?.toLocaleString()} | ₹${item.flatFees?.toLocaleString()} | ₹${item.totalPenalty?.toLocaleString()} | ₹${item.totalLiability?.toLocaleString()} | +${item.percentageIncrease}% |`).join('\n') || ''}

*Calculation Narrative:* ${p.narrative}
`;
    }
  }

  let chatSection = '';
  const chatList = messages && messages.length > 0 ? messages : (doc.chatHistory || []);
  if (chatList.length > 0) {
    chatSection = `### 5. Clause Q&A Chat Transcript
${chatList.map((m: ChatMessage) => `**[${m.timestamp}] ${m.role === 'user' ? 'Citizen' : 'AI Legal Guardian'}:**\n${m.text}\n`).join('\n')}
`;
  }

  return `# 🛡️ DocExplainer AI — Official Contract Risk Audit & Verification Certificate

**Verification Certificate ID:** DOC-${doc.docId.toUpperCase().slice(0, 12)}  
**Audit Timestamp:** ${now}  
**Document Analyzed:** ${doc.fileName || doc.docType || 'Uploaded Document'}  
**Verification Engine:** Amazon Bedrock Claude 3.5 Sonnet + AWS Lambda Deterministic Math  

---

## 1. Executive Health & Power Balance Diagnostic
- **Document Health Score:** **${health.healthScore}/100 (${health.ratingLabel})**
- **Power Asymmetry Balance:** **${health.asymmetryScore}% (${health.partyAName})** vs. **${100 - health.asymmetryScore}% (${health.partyBName})**
- **Critical Risk Flags Identified:** ${health.trapCount} Clauses
- **Unilateral Clauses:** ${health.unilateralClausesCount} Terms

---

## 2. Plain-Language Executive Summary
${doc.explanation || 'Summary not available.'}

${doc.keyDates && doc.keyDates.length > 0 ? `### Critical Deadlines & Key Dates:\n${doc.keyDates.map((d) => `- 📅 ${d}`).join('\n')}\n` : ''}

---

## 3. Structured Risk Flags & Trap Clauses
| Clause Reference | Financial Penalty / Term | Impact & Reason |
| :--- | :--- | :--- |
${doc.riskFlags?.map((f) => `| **${f.clause}** | \`${f.amount}\` | ${f.why} |`).join('\n') || '| No major risk flags detected | Standard | Document aligns with fair terms |'}

---

${mathSection}

---

${chatSection}

---

### Verification Stamp
*This audit was generated by DocExplainer AI on AWS Cloud (us-east-1). Deterministic calculations were executed by AWS Lambda without LLM arithmetic hallucination. This document serves as a factual clause verification report to aid in fair contract execution and negotiation.*
`;
}

export function downloadAuditReport(doc: DocumentData, messages?: ChatMessage[]) {
  const markdown = generateAuditReportMarkdown(doc, messages);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const cleanName = (doc.fileName || doc.docType || 'Document').replace(/[^a-zA-Z0-9]/g, '_');
  a.download = `DocExplainer_Audit_Certificate_${cleanName}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportChatTranscript(docId: string, messages: ChatMessage[]) {
  const content = `DOCEXPLAINER AI — CHAT CONVERSATION TRANSCRIPT\nDocument ID: ${docId}\nExported: ${new Date().toLocaleString()}\n------------------------------------------------------------\n\n` +
    messages.map((m) => `[${m.timestamp}] ${m.role === 'user' ? 'USER' : 'ASSISTANT'}:\n${m.text}\n\n`).join('------------------------------------------------------------\n\n');

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const cleanName = docId.replace(/[^a-zA-Z0-9]/g, '_');
  a.download = `DocExplainer_Chat_${cleanName}_${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function printAuditCertificate(_doc?: DocumentData) {
  window.print();
}

export const printAuditReport = printAuditCertificate;
